# Getting started {#getting_started}

**Chapter lead author: Pepa Aran**

TBC

Contents:

- Lecture (Beni): Data revolution, opportunities, challenges; explain relevance and why new methods are required
- installing environment
- workspace management
- R, RStudio
- R libraries, other libraries and applications

## Learning objectives

After you've gone over the lecture and solved the exercises, you should be able to:

- Work with R and RStudio on your computer
- Organize your workspace, using R projects
- Use R libraries, other libraries and applications
- Fork and clone a GitHub repository

## Tutorial

This tutorial will guide you through the process of installing an environment for working with the R programming language, managing your workspace, and using R libraries and other applications such as netcdf.

### Working with RStudio

First, you will need to install R and RStudio on your computer. R is a free, open-source programming language for statistical computing and data analysis, while RStudio is an integrated development environment (IDE) that makes it easier to work with R.
To install R and RStudio, download the installers for R (https://cran.r-project.org/) and RStudio (https://posit.co/download/rstudio-desktop/) corresponding to your OS, then double-click on the downloaded files and follow the on-screen instructions.



### Git

*Git* is a program for code version control and managing collaborative code development. The basic unit of a Git project is a *repository*, which usually contains multiple source code files that may be organised in (sub) directories. Git keeps track of the entire history of a repository in steps of *commits*. A commit is a "bundle" of multiple edits and additions of new files and is specified by the user. Since Git knows the entire history of all the files that have ever been added or removed to and from a repository, it allows you to recover previous versions of files (previous commits) and track changes between them. Git also allows you to have multiple versions of your repository (*branches*) for parallel developments on the same code base, but we will not use this feature. Since Git stores the entire history, the content of a Git repository should always be kept light. For example, it is advisable to only add code and other (small, <10 MB) plain text files to a repository, but not data, and no other outputs that is created by the code of the repository. 

A Git repository exists locally, that is, on your computer. But the power of Git plays out when your local repository has a counterpart in the cloud, for example on [GitHub](https://github.com). Git lets you *push* (upload) your commits to your repository's *remote* copy, and *pull* (download) changes that have been uploaded by your collaborator(s) or yourself from a different *clone* (local copy) of your repository.

### Installing R environment

### Workspace management

Having an organized workspace from the start of a project is key for reproducibility, making it easier to collaborate with others and also to revisit your own code in the future. Here we present some basics of workspace management:

- Create an *R project*.
- Create a folder structure.
- Use a Git repository.



On the GECO GitHub account, there is an open [R project repository template](https://github.com/computationales/R_proj_template) which you can take inspiration from. It also includes detailed instructions on how you can start your own R project repository from the template, using Git. This gets rid of the overhead of designing your folder structure for each project and helps you keep your code tidy.

### R libraries, other libraries and applications

This tutorial uses a set of libraries. Libraries provide a set of functions and/or other objects targeted for specific applications and are not available through base R. To run commands of this tutorial, make sure to install and load all packages on your computer. This can be done by:

```{r}
list_pkgs <- c("tidyverse")
new_pkgs <- list_pkgs[!(list_pkgs %in% installed.packages()[, "Package"])]
if (length(new_pkgs) > 0) install.packages(new_pkgs)
library(tidyverse)
```

In each chapter of this tutorial, you’ll find a similar statement to specify which package the respective chapter’s tutorial will use and to install them if not available.

## Exercises

## Solutions
