# Report requirements

## What is part of the report?

Throughout this book, you will find two kinds of exercises:

1.  Exercises where we provide a solution in Chapter \@ref(solutions), which **are not part** of your final report.

2.  Exercises in sections called "Report Exercise", which **are part** of your final report. These are:

    -   Chapter \@ref(datawrangling) (Create a tidy csv from a messy xlsx)

    -   Chapter \@ref(datavis) (Visualising running mean of \$CO_2\$ and telling a story about `airquality`)

    -   Chapter \@ref(codemgmt) (pair-exercise on GitHub)

    -   Chapter \@ref(regressionclassification) (Stepwise forward regression with minimum reproducible example)

    -   Chapter \@ref(supervisedmli) (Comparing model performance between linear model and KNN model; hypothesis on $k$-tuning and bias-variance trade-off)

    -   Chapter \@ref(supervisedmlii) (Training and testing on different Fluxnet sites)

The data to solve all these exercises is accessible [here](https://github.com/geco-bern/agds/tree/main/data).

To condense and deepen your understanding of the concepts that we teach, your report has to include **a short summary of each Chapter in no more than 10 sentences and in your own words**, which covers the main concepts of that Chapter.

## How do you hand in your report?

At the end of the course (exact date to be determined), you will send us a link to your GitHub account that holds the following three repositories:

-   Your **report repository** that holds your report as a .html file that is created from the respective .Rmd file that holds you report.

-   Two repositories from the exercise in Chapter \@ref(codemgmt):

    -   Your original repository that your friend cloned and where you accepted a pull request.

    -   Your forked repository from a friend to which you opened a pull request.

## How do we grade the report?

The grading of your report will depend on applying proper coding practices (code management and directory structure, using git and GitHub for version control, producing paper-ready figures, structuring your report with markdown headings and formatting, etc.) and correct interpretations of your results (never just output a figure or number, without giving a verbose answer the respective question). The sections where the report exercises are given, hold more detailed information of what we expect from you - pay attention to answer all questions!

*Important:* Reproducibility is key and and we expect that after completing this book, you are able to conduct reproducible workflows! Therefore, we will download your GitHub repository that holds your report and try to knit your .Rmd file. If we cannot reproduce your results, you cannot get a maximum grade. You can easily ensure that your report is reproducible by letting a friend run your code. Also note that from the commit history of your report repository, we can judge whether you followed good coding practices and committed and pushed your work on a regular basis or not.
